### ISSUE TITLE
The readme API links are incorrent

### ISSUE THREAD

**Issue by snyang** [Z3Prover/doc#7]
Following API links seems incorrect:
C++ API
.NET API
Python API

**Comment by simonstey** [comment]
fwiw, the correct links can be found here https://z3prover.github.io/api/html/:

[C++ API](https://z3prover.github.io/api/html/group__cppapi.html)
[.NET API](https://z3prover.github.io/api/html/namespace_microsoft_1_1_z3.html)
[Java API](https://z3prover.github.io/api/html/namespacecom_1_1microsoft_1_1z3.html)
[Python API](https://z3prover.github.io/api/html/namespacez3py.html) (also available in [pydoc format](https://z3prover.github.io/api/html/z3.html))
